### ISSUE TITLE
Shutdown hook not called when stopping redeployment

### ISSUE THREAD

**Issue by cescoffier** [reactiverse/vertx-maven-plugin#8]
When redeploying the application, the Vert.x shutdown hook is called. However, when stopping the redeployment (CTRL+C) it's not called.

**Comment by shawmanz32na** [comment]
This is also affecting our team. Here's what we know:
- It appears the original deployment is not stopped. After <kbd>ctrl+c</kbd>ing the Maven command process running the Vert.x application, there remains a Java process running (visible in the Process Explorer).
- This is commonly an issue when the Vert.x application starts an HTTP server or otherwise binds to a TCP port (such as when debugging). In these cases, the next launch will fail with "Address/port in use" errors.
- This appears to be a Windows-only issue. Those team members on Mac and Ubuntu don't have this issue.

**Comment by cescoffier** [comment]
I believe the Windows issue is a bit different. It seems that killing a process on windows is somewhat "random". This should be improved in Vert.x Core itself.

**Comment by shawmanz32na** [comment]
@cescoffier If the "Windows issue" is indeed different, is it being tracked and/or worked on? It's a huge annoyance for those of us trying to develop to have to manually locate and kill processes via the Process Explorer.

**Comment by tsegismont** [comment]
Closing this one. From my testing the shutdown hook is called on Windows and *NIX.
